# 1. ĐẦU VÀO (INPUT): Hút log từ đâu?
input {
  file {
    path => "/app/logs/app.log" # Đường dẫn này tương ứng với thư mục ./logs của bạn
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

# 2. BỘ LỌC (FILTER): Bóc tách dữ liệu
filter {
  # Dùng kỹ thuật Grok để tóm cổ cái TraceId trong ngoặc vuông [Trace-xxx]
  grok {
    match => { "message" => "\[%{DATA:trace_id}\]" }
    tag_on_failure => ["_grokparsefailure_traceid"]
  }
}

# 3. ĐẦU RA (OUTPUT): Ném đi đâu?
output {
  # Ném vào não bộ Elasticsearch
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "springboot-logs-%{+YYYY.MM.dd}" # Tạo index theo ngày
  }

  # Tiện tay in ra console của Docker để mình dễ debug
  stdout { codec => rubydebug }
}